import Head from 'next/head'

export default function Home() {
	return (
		<div>
			<Head>
				<title>Create Next App</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>

			<h1 className='text-7xl'>Next Tailwind Ecommerce</h1>
			<p>
				Lorem ipsum, dolor sit amet consectetur adipisicing elit. Facere
				deleniti a quod tenetur, nemo iste alias placeat veritatis fugiat vel
				voluptatem mollitia explicabo voluptatum corrupti eveniet totam odit,
				eligendi corporis!
			</p>
		</div>
	)
}
