import Head from 'next/head'
import { FC } from 'react'

const HomePage: FC = () => {
	return (
		<div>
			<Head>
				<title>Create Next App</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>

			<h1 className='text-7xl'>Next Tailwind Ecommerce</h1>
		</div>
	)
}

export default HomePage
